# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-rds-cluster-instance-group
  description: Terraform module to provision an RDS cluster instance pool with a dedicated endpoint
  homepage: https://cloudposse.com/accelerate
  topics: rds, cluster, instance-group, aws, terraform, terraform-module, reporting, replicas, slaves

